// Generated by gencpp from file ladder_data_demo/LadderData.msg
// DO NOT EDIT!


#ifndef LADDER_DATA_DEMO_MESSAGE_LADDERDATA_H
#define LADDER_DATA_DEMO_MESSAGE_LADDERDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/Imu.h>

namespace ladder_data_demo
{
template <class ContainerAllocator>
struct LadderData_
{
  typedef LadderData_<ContainerAllocator> Type;

  LadderData_()
    : pointcloud_1()
    , pointcloud_2()
    , imu_data()
    , arm_length(0.0)
    , amplitude_angle(0.0)
    , rotation_angle(0.0)  {
    }
  LadderData_(const ContainerAllocator& _alloc)
    : pointcloud_1(_alloc)
    , pointcloud_2(_alloc)
    , imu_data(_alloc)
    , arm_length(0.0)
    , amplitude_angle(0.0)
    , rotation_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_1_type;
  _pointcloud_1_type pointcloud_1;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_2_type;
  _pointcloud_2_type pointcloud_2;

   typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _imu_data_type;
  _imu_data_type imu_data;

   typedef double _arm_length_type;
  _arm_length_type arm_length;

   typedef double _amplitude_angle_type;
  _amplitude_angle_type amplitude_angle;

   typedef double _rotation_angle_type;
  _rotation_angle_type rotation_angle;





  typedef boost::shared_ptr< ::ladder_data_demo::LadderData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ladder_data_demo::LadderData_<ContainerAllocator> const> ConstPtr;

}; // struct LadderData_

typedef ::ladder_data_demo::LadderData_<std::allocator<void> > LadderData;

typedef boost::shared_ptr< ::ladder_data_demo::LadderData > LadderDataPtr;
typedef boost::shared_ptr< ::ladder_data_demo::LadderData const> LadderDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ladder_data_demo::LadderData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ladder_data_demo::LadderData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ladder_data_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ladder_data_demo': ['/home/zlzk/project/ros_ws/src/ladder_data_demo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ladder_data_demo::LadderData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ladder_data_demo::LadderData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ladder_data_demo::LadderData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ladder_data_demo::LadderData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ladder_data_demo::LadderData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ladder_data_demo::LadderData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ladder_data_demo::LadderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a1c337e572fb5eb08f9b90535f31829";
  }

  static const char* value(const ::ladder_data_demo::LadderData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a1c337e572fb5ebULL;
  static const uint64_t static_value2 = 0x08f9b90535f31829ULL;
};

template<class ContainerAllocator>
struct DataType< ::ladder_data_demo::LadderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ladder_data_demo/LadderData";
  }

  static const char* value(const ::ladder_data_demo::LadderData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ladder_data_demo::LadderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 pointcloud_1\n\
sensor_msgs/PointCloud2 pointcloud_2\n\
sensor_msgs/Imu imu_data\n\
float64 arm_length\n\
float64 amplitude_angle\n\
float64 rotation_angle\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Imu\n\
# This is a message to hold data from an IMU (Inertial Measurement Unit)\n\
#\n\
# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n\
#\n\
# If the covariance of the measurement is known, it should be filled in (if all you know is the \n\
# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n\
# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n\
# data a covariance will have to be assumed or gotten from some other source\n\
#\n\
# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n\
# estimate), please set element 0 of the associated covariance matrix to -1\n\
# If you are interpreting this message, please check for a value of -1 in the first element of each \n\
# covariance matrix, and disregard the associated estimate.\n\
\n\
Header header\n\
\n\
geometry_msgs/Quaternion orientation\n\
float64[9] orientation_covariance # Row major about x, y, z axes\n\
\n\
geometry_msgs/Vector3 angular_velocity\n\
float64[9] angular_velocity_covariance # Row major about x, y, z axes\n\
\n\
geometry_msgs/Vector3 linear_acceleration\n\
float64[9] linear_acceleration_covariance # Row major x, y z \n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ladder_data_demo::LadderData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ladder_data_demo::LadderData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointcloud_1);
      stream.next(m.pointcloud_2);
      stream.next(m.imu_data);
      stream.next(m.arm_length);
      stream.next(m.amplitude_angle);
      stream.next(m.rotation_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LadderData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ladder_data_demo::LadderData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ladder_data_demo::LadderData_<ContainerAllocator>& v)
  {
    s << indent << "pointcloud_1: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud_1);
    s << indent << "pointcloud_2: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud_2);
    s << indent << "imu_data: ";
    s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.imu_data);
    s << indent << "arm_length: ";
    Printer<double>::stream(s, indent + "  ", v.arm_length);
    s << indent << "amplitude_angle: ";
    Printer<double>::stream(s, indent + "  ", v.amplitude_angle);
    s << indent << "rotation_angle: ";
    Printer<double>::stream(s, indent + "  ", v.rotation_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LADDER_DATA_DEMO_MESSAGE_LADDERDATA_H
